name: Python Package using Conda

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conda
        uses: ./.github/actions/setup-conda@main
        with:
          python-version: '3.10'
          environment-file: 'environment.yaml'
      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conda
        uses: ./.github/actions/setup-conda@main
        with:
          python-version: '3.10'
          environment-file: 'environment.yaml'
      - name: Test with pytest
        run: |
          conda install pytest
          pytest